[package]
name = "cash_flow_rust"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
helix = "0.7.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
